version: '3.9'

services:
  sakila_mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sakila_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
